#!/bin/bash

# This file can be adjusted to specify the python installation 
# you want to use

# uncomment use a pyenv virtualenv
export PATH="${HOME}/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
pyenv activate myenv3

# uncomment to use a virtual environment
#source /path/to/virtualenv/bin/activate

# by default, if nothing is activated, the default python 
# environment is used. We strongly discurage to setup esprit
# like this.


export PATH=$PATH:/share/apps/genomics/mafft-7.310/bin:/share/apps/genomics/FastTree-2.1.10:./
export MAFFT_BINARIES="/share/apps/genomics/mafft-7.310/libexec/mafft/"
if [ ! -s FastTree ] ; then
    ln -s $(which FastTreeMP) FastTree
fi
